### PR TITLE
compatability for 0.107.6+

### LINKED ISSUE #12: 0.107.6 Incompatable?
HA-OUR-GROCERIES VERSION: 1.3.0
worked in ha 0.107.5 no problems... soon as i upgrade to 0.107.6:

```3/24/2020 10:52:39 AMERROR: ourgroceries 1.2.3 has requirement aiohttp==3.5.4, but you'll have aiohttp 3.6.1 which is incompatible.
3/24/2020 10:52:39 AM    ERROR: Command errored out with exit status 1:
3/24/2020 10:52:39 AM     command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hr04q8wo/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hr04q8wo/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-t94b_9sw/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/lxml
3/24/2020 10:52:39 AM         cwd: /tmp/pip-install-hr04q8wo/lxml/
3/24/2020 10:52:39 AM    Complete output (88 lines):
...
...
3/24/2020 10:52:39 AM  ERROR: Failed building wheel for lxml
3/24/2020 10:52:39 AMERROR: saltbox 0.1.3 has requirement beautifulsoup4==4.8.2, but you'll have beautifulsoup4 4.7.1 which is incompatible.
3/24/2020 10:52:39 AMERROR: saltbox 0.1.3 has requirement idna==2.8, but you'll have idna 2.9 which is incompatible.
3/24/2020 10:52:39 AMERROR: saltbox 0.1.3 has requirement requests==2.22.0, but you'll have requests 2.23.0 which is incompatible.
3/24/2020 10:52:39 AMERROR: saltbox 0.1.3 has requirement soupsieve==1.9.5, but you'll have soupsieve 2.0 which is incompatible.
3/24/2020 10:52:39 AMERROR: saltbox 0.1.3 has requirement urllib3==1.25.7, but you'll have urllib3 1.25.8 which is incompatible.
3/24/2020 10:52:39 AMERROR: motorparts 1.1.0 has requirement beautifulsoup4==4.5.1, but you'll have beautifulsoup4 4.7.1 which is incompatible.
3/24/2020 10:52:39 AMERROR: gearbest-parser 1.0.7 has requirement beautifulsoup4==4.6.0, but you'll have beautifulsoup4 4.7.1 which is incompatible.
3/24/2020 10:52:39 AMERROR: ourgroceries 1.2.3 has requirement aiohttp==3.5.4, but you'll have aiohttp 3.6.1 which is incompatible.
...
...
3/24/2020 10:52:39 AMERROR: Command errored out with exit status 1: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hr04q8wo/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hr04q8wo/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-t94b_9sw/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/lxml Check the logs for full command output.
3/24/2020 10:52:39 AM2020-03-24 10:52:39 ERROR (MainThread) [homeassistant.setup] Setup failed for ourgroceries: Requirements for ourgroceries not found: ['ourgroceries==1.2.3'].
```

### PR DESCRIPTION
**Pull request by pironic**
Now that you removed the lxml dependency in py-our-groceries this is a simple fix. 

tested this to work against docker images 0.107.6 and 0.108.3: both work.
this will resolve #12 

sorry about the last pull ... this one is actually tested :)

(side note: i apparently had an extra line change in my commit for the url... both urls dont' work but this one at least looks better... if you want, i can alter the commit)

### CODE REVIEW

**Comment by rpitera** [comment]
Tested this just by manually making the changes to manifest.json and it brought back the sensor and data - awesome!

But there seems to be an issue with the custom card now; I cannot expand any of the lists to show the items.  Adding a new item works and the lists are showing the correct number of items - I just can't expand the lists.  Could the changes in py-our-groceries require an update to the code in the card by any chance?

This is what I'm seeing in the dev console;

```
/api/ourgroceries:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
index.js:113 Objecterror: error: "Response error: 500"status_code: 500body: "500 Internal Server Error↵↵Server got itself in trouble"__proto__: Objectconstructor: ƒ Object()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()hasOwnProperty: ƒ hasOwnProperty()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toString: ƒ toString()valueOf: ƒ valueOf()toLocaleString: ƒ toLocaleString()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()__proto__: Objectconstructor: ƒ Object()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()hasOwnProperty: ƒ hasOwnProperty()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toString: ƒ toString()valueOf: ƒ valueOf()toLocaleString: ƒ toLocaleString()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
getListItems @ index.js:113
/api/ourgroceries:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
index.js:113 Object
getListItems @ index.js:113
/api/ourgroceries:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
index.js:113 Object
getListItems @ index.js:113
/api/ourgroceries:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
index.js:113 Object
getListItems @ index.js:113
```

**Comment by ljmerza** [comment]
added in v1.3.4

**Comment by rpitera** [comment]
Any fix for the custom card?

**Comment by ljmerza** [comment]
this looks like a loading of the resource issue. It's best to open a new issue and post the HASS logs when enabling debugging for the our-groceries component

**Comment by rpitera** [comment]
No problem. Should I open it in the app or the card repo?  I posted the issue here because the new component hadn't been released yet.

**Comment by rpitera** [comment]
I know this has already been merged but I wanted to update my custom card issue to say that with the 1.3.5 release my issue is gone and everything works again.  Thanks!

**Pull request merged**
